### ISSUE TITLE
Bug Texture

### ISSUE THREAD

**Issue by Willtom999** [alvin0319/CustomItemLoader#44] opened 2021-07-18 19:00 UTC
not know normal the texture is large you can solve the problem of the plugin?
![0252C8C1-4085-42F8-BC99-B3F7B4E1CEFC](https://user-images.githubusercontent.com/83521998/126079177-935f7656-97e7-4ec1-9217-e7fea0e41e77.png)
![Uploading 688E94E0-0FD5-41C6-B3BA-B4CA5A611966.png…]()

**Comment by alvin0319** [comment] 2021-07-19 00:35
That's not bug. You have to use correct image which satisfies Minecraft's texture size.
This was expected.

duplicate of #18

**Closed by alvin0319** 2021-07-19 00:35 UTC
Labels: bug
