### ISSUE TITLE
armor resistance does not work

### ISSUE THREAD

**Issue by Auslatos** [alvin0319/CustomItemLoader#92] opened 2022-03-04 05:09 UTC
**Describe the bug**
I tried to pvp with one of my custom armor but the resistance is not working im getting killed after 2 hit

This is my config for a chestplate :
  eroplexium_chestplate:
    id: 505
    meta: 0
    namespace: eroplex:eroplexium_chestplate
    name: eroplexium_chestplate
    texture: eroplexium_chestplate
    armor: true
    armor_slot: chest
    defence_points: 11 # Defence points of armor
    armor_class: diamond # Default is diamond, feel free to send feedback to me
    durable: true
    max_durability: 750
    max_stack_size: 1

 - PocketMine-MP Version: latest
 - CustomItemLoader Version: latest

Please if I got something wrong can you tell me what or correct this :D

**Comment by alvin0319** [comment] 2022-03-04 06:19
Latest is not a valid version. try `/ver` and `/version CustomItemLoader` and paste output here.

**Comment by Auslatos** [comment] 2022-03-04 14:46
CustomItemLoader 2.3.1 and Pocketmine 4.2.1 not the latest but its doing it in all version for me

**Comment by Auslatos** [comment] 2022-03-08 02:42
so...

**Comment by Auslatos** [comment] 2022-03-13 06:20
?

**Comment by Auslatos** [comment] 2022-03-13 06:20
> 

?

**Comment by alvin0319** [comment] 2022-06-04 02:58
Closing due to cannot reproduce the issue.

**Closed by alvin0319** 2022-06-04 02:59 UTC
Labels: bug
